version: "3.8"
services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /usr/app/node_modules
    env_file:
      - .env
    depends_on: 
      - mongo
    networks:
      - nodetodo-net
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: node-todo
    networks:
      - nodetodo-net

volumes:
  mongodata:
    driver: local
networks:
  nodetodo-net: