services:
  api:
    build: .
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - /usr/app/node_modules
    env_file:
      - .env
    depends_on: 
      - mongo
    networks:
      - nodetodo-net

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodata:/data/db
    networks:
      - nodetodo-net

volumes:
  mongodata:

networks:
  nodetodo-net: